=== Peter-Plus/Deadzone-Protocol/Legacy/ForgeKit(old)/schemas/pose.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "pose.v1",
  "type": "object",
  "properties": {
    "schema": {
      "const": "pose.v1"
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$"
    },
    "rig": {
      "const": "humanoid.v1"
    },
    "bones": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "object",
        "properties": {
          "rotation": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 3,
            "maxItems": 3
          },
          "position": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 3,
            "maxItems": 3
          }
        },
        "required": [],
        "additionalProperties": false,
        "minProperties": 1
      }
    }
  },
  "required": [
    "schema",
    "id",
    "rig",
    "bones"
  ],
  "additionalProperties": false
}

=== Peter-Plus/Deadzone-Protocol/Legacy/ForgeKit(old)/assets/definitions/poses/humanoid_stand.pose.json
{
  "schema": "pose.v1",
  "id": "pose.humanoid.stand",
  "rig": "humanoid.v1",
  "bones": {
    "Hips": {
      "rotation": [
        0,
        0,
        0
      ]
    },
    "UpperArm_L": {
      "rotation": [
        0,
        0,
        -82
      ]
    },
    "UpperArm_R": {
      "rotation": [
        0,
        0,
        82
      ]
    }
  }
}
